############################## Site settings ##############################

title: M.A.K.E.
subtitle: Multidisciplinary Analytical Kinesthetic Education
email: make@make.skule.ca
senpai: Henry Lu
project: https://github.com/nanosmasher/make.skule.ca

# Google's indigo palette
color:
    D50: e8eaf6
    D100: c5cae9
    D200: 9fa8da
    D300: 7986cb
    D400: 5c6bc0
    D500: 3f51b5
    D600: 3949ab
    D700: 303f9f
    D800: 283593
    D900: 1a237e
    A100: 8c9eff
    A200: 536dfe
    A400: 3d5afe
    A700: 304ffe

markdown: kramdown
permalink: '/events/:short_year:month:day/'
relative_permalinks: false
include: [.htaccess]
exclude: [LICENSE,README.md]

############################## Stuff you can touch  ##############################

keywords: ['Multidisciplinary','Analytical','Kinesthetic','Education','UofT','Skule','Engineering','Club','Academic','First-Year']

description: 'MAKE aims to apply scientific concepts relevant to first year engineering curriculum to practical projects. We hold sessions covering multidisciplinary engineering topics, providing students the opportunity to learn principles behind real world applications by building prototypes. We also focus on the design aspect of engineering, an important skill usually under-emphasized in a classroom setting. Through our events, engineering students will gain a better understanding of each engineering discipline as well as realize the applicability of their first year engineering education at UofT.'

news: 'Cryptography: Thues. Nov. 10th from 6-8pm in GB144'

sponsors: ['CHEM','CIV','ECE','ENGSCI','MIE','MSE','ALUMNI']

team:
-  name: 'Micah Stickel'
   pos: 'Club Advisor'
   year: 'First Year Engineering Chair'
   pic: 'MS'
-  name: ' '
   pos: ' '
   year: ' '
   pic: 'blank'
-  name: 'Alan Li'
   pos: 'Co-President'
   year: 'CHEM 1T6'
   pic: 'AL'
-  name: 'Janany Ragunathan'
   pos: 'Co-President'
   year: 'CIV 1T4 + PEY'
   pic: 'JR'
-  name: 'Kevin Ton'
   pos: 'Vice-President'
   year: 'MSE 1T7'
   pic: 'KT'
-  name: 'Angela Chen'
   pos: 'Sponsorship Director'
   year: 'ENGSCI 1T8'
   pic: 'AC'
-  name: 'Katherine Junyi Sun'
   pos: 'Finance Director'
   year: 'ECE 1T8'
   pic: 'KJS'
-  name: 'Ijaz Peerbocus'
   pos: 'Marketing Director'
   year: 'ENGSCI 1T8'
   pic: 'IP'
-  name: 'Florence Chan'
   pos: 'Logistics Director'
   year: 'ENGSCI 1T8'
   pic: 'FC'
-  name: 'Patrick Meredith-Karam'
   pos: 'Technical Lead'
   year: 'ENGSCI 1T8'
   pic: 'PM-K'
-  name: 'Henry Lu'
   pos: 'Webmaster'
   year: 'MSE 1T7'
   pic: 'HL'
